[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.devnet]
meridian = "6SaMPmMDFZD6pg4NwK13Cph6YSSiZQwzBsbhrroRUJdy"

[programs.localnet]
meridian = "6SaMPmMDFZD6pg4NwK13Cph6YSSiZQwzBsbhrroRUJdy"

[provider]
cluster = "devnet"
wallet = "./keypairs/admin.json"

[scripts]
test = "npx tsx node_modules/mocha/bin/mocha -t 1000000 tests/**/*.ts"

[hooks]

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU"
