import * as anchor from "@coral-xyz/anchor";
import { AnchorProvider, Program, Wallet } from "@coral-xyz/anchor";
import { Connection, Keypair } from "@solana/web3.js";
import { Config, readKeypairBytes } from "./config.js";
// IDL is generated by `anchor build` into target/idl/meridian.json.
// We import it via require() so this module compiles cleanly even before
// the IDL exists; jobs error fast at runtime if it's missing.

export interface ProgramContext {
  connection: Connection;
  provider: AnchorProvider;
  wallet: Wallet;
  program: Program;
}

export function loadProgram(cfg: Config): ProgramContext {
  const connection = new Connection(cfg.rpcUrl, "confirmed");
  const keypair = Keypair.fromSecretKey(readKeypairBytes(cfg.automationKeypairPath));
  const wallet = new anchor.Wallet(keypair);
  const provider = new AnchorProvider(connection, wallet, { commitment: "confirmed" });

  // Load the IDL emitted by `anchor build`. Relative path from this file
  // when compiled — adjust if your build output differs.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const idl = require("../../target/idl/meridian.json");
  const program = new Program(idl, provider);

  return { connection, provider, wallet, program };
}
